import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/Navbar";
import HomePage from "./components/HomePage";
import About from "./components/About";
import Projects from "./components/Projects";
import Contact from "./components/Contact";
import Footer from "./components/Footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mary|Frontend developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <Navbar />
        <div className=" px-10 sm:px-20 ">
          <HomePage />
          <About />
          <Projects />
          <Contact />
        </div>
        <div className="px-10   sm:px-20 bg-[#2f2e41]">
          <Footer />
        </div>
      </div>
    </div>
  );
};

export default Home;
